# Generated by Django 4.2.28 on 2026-09-24 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('LinkedIn', 'LinkedIn'), ('Phone Call', 'Phone Call'), ('In-Person / Camp', 'In-Person / Camp')], default='Email', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Ready', 'Ready'), ('Sent', 'Sent'), ('Awaiting Response', 'Awaiting Response'), ('Follow-up Due', 'Follow-up Due'), ('Responded', 'Responded'), ('Positive', 'Positive'), ('Declined', 'Declined'), ('Closed', 'Closed')], default='Draft', max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, help_text='Notes or exact response received from organization')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreaches', to='contacts.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreaches', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
