# Generated by Django 4.2.28 on 2026-09-24 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(default='B.Sc. Computer Engineering', max_length=255)),
                ('skills', models.TextField(default='Python, Django, FastAPI, PostgreSQL, Linux, Docker, REST APIs, Git, Systems Architecture', help_text='Comma separated list of core technical skills')),
                ('interests', models.TextField(default='Backend Engineering, IT Infrastructure, Information Management, Technical Support, Cloud Engineering', help_text='Primary technical interest areas')),
                ('preferred_locations', models.TextField(default='Abuja, Kwara, Lagos, Ibadan', help_text='Target NYSC PPA cities or states')),
                ('nysc_batch', models.CharField(blank=True, default='2026 Batch A Stream 1', max_length=100)),
                ('nysc_state', models.CharField(blank=True, default='FCT Abuja', max_length=100)),
                ('cv_summary', models.TextField(blank=True, default='Computer Engineering graduate with hands-on expertise building scalable Python/Django applications and managing backend infrastructure. Seeking NYSC PPA position in software development or IT management.')),
                ('additional_context', models.TextField(blank=True, help_text='Any additional context for AI outreach generation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
