# Generated by Django 4.2.28 on 2026-09-24 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=150)),
                ('source_type', models.CharField(choices=[('Website', 'Website'), ('Careers Page', 'Careers Page'), ('LinkedIn', 'LinkedIn'), ('News Article', 'News Article'), ('Job Listing', 'Job Listing'), ('Public Directory', 'Public Directory'), ('User Input', 'User Input')], default='Website', max_length=50)),
                ('content_excerpt', models.TextField(blank=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Completed', 'Completed'), ('Partially Completed', 'Partially Completed'), ('Failed', 'Failed')], default='Queued', max_length=50)),
                ('depth', models.CharField(choices=[('Quick', 'Quick'), ('Standard', 'Standard'), ('Deep', 'Deep')], default='Standard', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_jobs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField(help_text='What this evidence claims')),
                ('evidence_type', models.CharField(choices=[('NYSC Acceptance Evidence', 'NYSC Acceptance Evidence'), ('Technical Department/Roles', 'Technical Department/Roles'), ('Graduate Recruitment Program', 'Graduate Recruitment Program'), ('Target Location Presence', 'Target Location Presence'), ('Direct Careers Contact', 'Direct Careers Contact')], default='Technical Department/Roles', max_length=50)),
                ('excerpt', models.TextField(blank=True, help_text='Exact excerpt or snippet from source')),
                ('confidence', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Unknown', 'Unknown')], default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='organizations.organization')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='research.source')),
            ],
        ),
    ]
